function model = qdfrntTrain(source, secret, kt, intensity)
%qdfrntTrain - train svm model to restore secret watermark
%
% - Arguments:
%       - source [nxnx3 double matrix] matrix of colorful source image
%       - secret [1xm binary vector] vector of secret sequence
%       - kt [8x8 double matrix] kernel matrix of transform, can be generated by function 'qdfrntKernel'
%       - intensity [double] the intensity of watermarking
%
% - Returns:
%       - model [SVM model] train result model

end