function output = dfrnt(source, r)
%dfrnt - one-dimension DFRNT
%
% - Description:
%       the one dimension discrete fractional random transform
%
% - Arguments:
%       - source [1xn double matrix] 1xn source signal vector
%       - r [nxn double matrix] kernel matrix of transform, get be generated by function 'dfrntKernel'
%
% - Returns:
%       - output [1xn double matrix] the output signal vector 

% do the transposition to source matrix
source = source';

% get the output matrix
output = r * source;
output = output';

end